### ISSUE TITLE
running example files

### ISSUE THREAD

**Issue by ppathak8** [vortex-exoplanet/HEEPS#11]
The example scripts have been moved inside heeps, I think it will be good to keep it outside, makes it easier to show how each module works. I will be also adding an end-end example.  

And metis_hci has been removed, I think its good to keep it for now. Easier to do coronagraphic propagation for various modes.

**Comment by ChrisDelaX** [comment]
Good idea. I would just suggest to create a container for potential multiple examples in HEEPS/Example.

Prashant, you assigned this issue to Valentin Christiaens instead of me :) no worries, you're not the first one, nor the last one to do this common confusion.

**Comment by ChrisDelaX** [comment]
Fixed in 615dc5b

**Comment by ppathak8** [comment]
haha, sorry about that
