### ISSUE TITLE
parallactic angle definition needs fixing in ADI.py

### ISSUE THREAD

**Issue by ChrisDelaX** [vortex-exoplanet/HEEPS#13]
parallactic angle should vary around 0 or 180 degrees, which is currently not the case:
```python
In [1]: import numpy as np
In [2]: length = 10
In [3]: np.linspace(-160, 160, length)
Out[3]:
array([-160.        , -124.44444444,  -88.88888889,  -53.33333333,
        -17.77777778,   17.77777778,   53.33333333,   88.88888889,
        124.44444444,  160.        ])
```
![test_adi_-160_160](https://user-images.githubusercontent.com/12912366/48128944-57b96e80-e288-11e8-9099-fbefb74cf729.png)

Instead of -160 to 160 deg, it could be defined from 160 to -160
```python
In [4]: (np.linspace(160, 200, length) + 180) % 360 - 180
Out[4]:
array([ 160.        ,  164.44444444,  168.88888889,  173.33333333,
        177.77777778, -177.77777778, -173.33333333, -168.88888889,
       -164.44444444, -160.        ])
```
![test_adi_160_-160](https://user-images.githubusercontent.com/12912366/48129120-de6e4b80-e288-11e8-94e0-b8e1509b1ee7.png)
Using VIP, this seems to produce the same result as using 160 to 200 deg, 
![test_adi_160_200](https://user-images.githubusercontent.com/12912366/48129047-af57da00-e288-11e8-8955-04da0be3ec91.png)
or even from -20 to 20 deg
![test_adi_-20_20](https://user-images.githubusercontent.com/12912366/48129053-b4b52480-e288-11e8-9f8b-00eafda0c705.png)

**Comment by ppathak8** [comment]
yeah, this is old, sorry I didn't update.
