### ISSUE TITLE
Bug in adi.py + suggestion

### ISSUE THREAD

**Issue by GillesOrban** [vortex-exoplanet/HEEPS#17]
Line 199 of adi.py is probably a hack to be removed:
```cc_pp = 0 ```

I would also have a suggestion for the function adi: to add the possibility for a user defined tag name (e.g. variable ``tagname=''``) that would be appended to ``savename``.
Might slightly improve backstracking of simulations...

**Comment by ChrisDelaX** [comment]
added tagname as suggested, thanks!
