### ISSUE TITLE
Inconsistency in 'pupil.py'

### ISSUE THREAD

**Issue by GillesOrban** [vortex-exoplanet/HEEPS#19]
There is a inconsistency in the definition of the variable 'pupil_file' in the function pupil
See
`pupil_file = {`
and then line 37 
`if pupil_file is None:`

**Comment by ChrisDelaX** [comment]
Thanks, I changed line 37 to:
    if conf['pupil_file'] is None and conf['N_mis_segments'] == 0:

Should make more sense.

**Comment by GillesOrban** [comment]
This change has apparently disappeared...
