### ISSUE TITLE
pupil visualization tool

### ISSUE THREAD

**Issue by ChrisDelaX** [vortex-exoplanet/HEEPS#2]
Translate Brunella's IDL routine into python, using PROPRER library.
Integrate into HEEPS.

Tibor has to ask Leo and ROy if this is already implemented in METIS simulator. 
If yes, we need to cross-validate results.

**Comment by oabsil** [comment]
After checking with Leo, the pupil is currently not implemented in the METIS simulator, and will not be implemented in the near future.

**Comment by ChrisDelaX** [comment]
Update: pupil function should be called after an "init" that calculates some stuff such as npupil, beam ratio,...
Propagation should be removed from the pupil function, and called from a standardized propagation function (used also for other propagation steps)
