### ISSUE TITLE
choose fastest between PROPER "prop_add_phase" and "prop_multiply"

### ISSUE THREAD

**Issue by ChrisDelaX** [vortex-exoplanet/HEEPS#21]

**Comment by ChrisDelaX** [comment]
### PROPER wavefront properties
```
In [39]: wfo.__dict__
Out[39]:
{'_wfarr': array([[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        ...,
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j]]),
 '_lamda': 3.8e-06,
 '_dx': 0.14691666111949792,
 '_beam_type_old': 'INSIDE_',
 '_reference_surface': 'PLANAR',
 '_R_beam': 0.0,
 '_R_beam_inf': 1,
 '_z': 0.0,
 '_z_w0': 0.0,
 '_w0': 18.5,
 '_z_Rayleigh': 282950022.55029124,
 '_propagator_type': 'INSIDE__TO_INSIDE_',
 '_current_fratio': 1000000000.0,
 '_diam': 37.0,
 '_ngrid': 1024}
```
### Show phase and amplitude
```
In [42]: wf = deepcopy(wfo)

In [43]: amp0 = impro.crop_img(proper.prop_get_amplitude(wf), npupil)

In [44]: phi0 = impro.crop_img(proper.prop_get_phase(wf), npupil)

In [45]: np.max(np.abs(phi0))
Out[45]: 0.0

In [46]: close('all');figure();imshow(amp0);colorbar();figure();imshow(phi0);colorbar()
Out[46]: <matplotlib.colorbar.Colorbar at 0x7febbcf1a668>
```

<img width="1097" alt="Screenshot 2019-11-16 at 19 30 49" src="https://user-images.githubusercontent.com/12912366/68997501-9fb19f00-08a7-11ea-9c2d-073a8658294c.png">

### Speed test: ```prop_multiply``` vs ```prop_add_phase``` 

Test shows similar speed, but differences in phase.
```
In [55]: wf = deepcopy(wfo)

In [56]: timeit(proper.prop_multiply(wf, np.exp(1j*(2*np.pi/3.8)*ncpa)))
17.6 ms ± 68.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [57]: amp1 = impro.crop_img(proper.prop_get_amplitude(wf), npupil)

In [58]: phi1 = impro.crop_img(proper.prop_get_phase(wf), npupil)

In [59]: wf = deepcopy(wfo)

In [60]: timeit(proper.prop_add_phase(wf, ncpa*1e-9))
16.2 ms ± 531 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [61]: amp2 = impro.crop_img(proper.prop_get_amplitude(wf), npupil)

In [62]: phi2 = impro.crop_img(proper.prop_get_phase(wf), npupil)

```
### Comparison:
```
In [98]: close('all');figure();imshow(phi1);colorbar();figure();imshow(phi2);colorbar()
Out[98]: <matplotlib.colorbar.Colorbar at 0x7febee02d128>
```
<img width="1071" alt="Screenshot 2019-11-16 at 19 00 20" src="https://user-images.githubusercontent.com/12912366/68997139-7858d300-08a3-11ea-8885-81e672b46796.png">

```
In [99]: close('all');figure();imshow(amp1);colorbar();figure();imshow(amp2);colorbar()
Out[99]: <matplotlib.colorbar.Colorbar at 0x7febd8bcdd68>
```

<img width="1087" alt="Screenshot 2019-11-16 at 19 00 55" src="https://user-images.githubusercontent.com/12912366/68997141-7f7fe100-08a3-11ea-8bbb-2e8a7c0f049c.png">

### Residuals
In [123]: residuals = (phi1-phi2+np.pi)%(2*np.pi) - np.pi
In [124]: close('all');figure();imshow(residuals);colorbar();

<img width="755" alt="Screenshot 2019-11-16 at 19 36 03" src="https://user-images.githubusercontent.com/12912366/68997594-82310500-08a8-11ea-93d5-38f0e8193585.png">

@ppathak8 : could you take a look at this test and tell me if I'm missing something?

**Comment by oabsil** [comment]
Couldn't it be an issue with units?
"In [56]: timeit(proper.prop_multiply(wf, np.exp(1j*(2*np.pi/3.8)\*ncpa)))"
--> seems to assume ncpa to be in µm (as it is divided by 3.8µm)
"In [60]: timeit(proper.prop_add_phase(wf, ncpa\*1e-9))"
--> seems to assume ncpa to be in nm.
Regarding the timing, the result looks pretty consistent with how both functions are coded (i.e., they are almost exactly the same). The only difference in that in the first case, you do the conversion from OPD to phase yourself in the call, while in the second case you let the function take care of it.
Hope this helps.

**Comment by ChrisDelaX** [comment]
Thanks Olivier, it was exactly a units issue. It's often the same problem, and it comes from the fact ncpa screen is in nm and SCAO residuals in µm. It's high time I implement astropy units everywhere in HEEPS to avoid that kind of mistakes.

### New test:
```
In [135]: wf = deepcopy(wfo)

In [136]: timeit(proper.prop_multiply(wf, np.exp(1j*(2*np.pi/3800)*ncpa)))
19 ms ± 89.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [137]: amp1 = impro.crop_img(proper.prop_get_amplitude(wf), npupil)

In [138]: phi1 = impro.crop_img(proper.prop_get_phase(wf), npupil)

In [139]: wf = deepcopy(wfo)

In [140]: timeit(proper.prop_add_phase(wf, ncpa*1e-9))
17.2 ms ± 355 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [141]: amp2 = impro.crop_img(proper.prop_get_amplitude(wf), npupil)

In [142]: phi2 = impro.crop_img(proper.prop_get_phase(wf), npupil)

In [143]: close('all');figure();imshow(phi1);colorbar();figure();imshow(phi2);colorbar()
Out[143]: <matplotlib.colorbar.Colorbar at 0x7febec76b198>
```
<img width="1082" alt="Screenshot 2019-11-16 at 22 12 34" src="https://user-images.githubusercontent.com/12912366/68999264-b0214400-08be-11ea-9611-8d33a21a9aab.png">

### Difference between 2 methods:
```
In [149]: diff = (phi1-phi2+np.pi)%(2*np.pi) -np.pi

In [150]: np.mean(diff)
Out[150]: -3.890923318097644e-16

In [151]: np.std(diff)
Out[151]: 1.023685036965738e-14

In [152]: close('all');figure();imshow(diff);colorbar();
```
<img width="507" alt="Screenshot 2019-11-16 at 22 20 35" src="https://user-images.githubusercontent.com/12912366/68999360-756bdb80-08bf-11ea-9ba0-2d31ba5e2cab.png">

**Comment by ChrisDelaX** [comment]
As a conclusion, I suggest that I change the code so that it always uses the same proper.prop_add_phase when adding phase, which is more explicit than the other method.

The advantage will be that, when running simulations with a combination of atmosphere residuals, petal piston, and NCPA, the frames will be:
1/ summed to a single frame
2/ then padded (once)
3/ then applied to the wavefront (once).
