### ISSUE TITLE
Inconsistency in wavefront_aberrations

### ISSUE THREAD

**Issue by GillesOrban** [vortex-exoplanet/HEEPS#23]
The function `wavefront_aberrations` allows as input zernike indices and their respective coefficients (`zern_inds` and `zernike`).
This is typically used to inject jitter (tip-tilt or Z2 and Z3) which are specified in mas and converted in this function in [nm rms] before being passed to proper.
This is ok as long as one use tip and tilt.

For higher order modes this conversion (mas -> nm rms) is not correct.

The code should be modified and should distinguish between tip-tilt and higher-order modes and use appropriate units (rad rms or nm rms). Also, the function should be documented, so the user knows which units she/he has to use

**Comment by ChrisDelaX** [comment]
Addressed by ebb1f33c351bea87ab6f56c8424984744280cb14
