### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by ppathak8** [vortex-exoplanet/HEEPS#25]
In metis_modes.py:
 
if conf['mode'] == 'ELT': 
        conf['LS_params'] = [1., -0.3, 0.]  # means no Lyot stop
        lyotstop(wf, conf)

If simulating the ELT mode 1st, LS parameters get updated and later running other modes get screwed up. So for ELT mode keep is empty.

**Comment by ChrisDelaX** [comment]
Fixed by e613bc33f4227e44b177ed53bf9fbbc28fd0c5b4
