### ISSUE TITLE
update gitignore

### ISSUE THREAD

**Issue by ChrisDelaX** [vortex-exoplanet/HEEPS#3]
__pychache__ folders appear in my Github Desktop as if they wanted to be sync'ed in HEEPS Github

**Comment by ppathak8** [comment]
It has to do with the compilation of the Python module when importing, this is pretty standard. Is this what you see "__pycache__"

**Comment by ChrisDelaX** [comment]
Yes, software compilation creates files in your local environment. 
It is common practice to avoid syncing those files, by adding them to the "git ignore list" in a .gitignore file, such as in this example (this is a template I use for various projects):
https://github.com/ChrisDelaX/HCIFS/blob/master/.gitignore

**Comment by ppathak8** [comment]
Ohh I see what you mean. As you may have realized, I am fairly new to the Github, so didn't realize you could do that. Thanks

**Comment by ChrisDelaX** [comment]
No worries at all Prashant. I am also learning more stuff from you. This is
precisely why I started to create specific "issues". This way we can push
smaller commits for each topic. It adds transparency and allows everyone to
learn from each other.
