### ISSUE TITLE
import proper - which library does this refer to?

### ISSUE THREAD

**Issue by astronomyk** [vortex-exoplanet/HEEPS#35]
Hi there,

I just cloned HEEPS and wanted to run the `run_heeps.py` script for the APP mode. I needed to install the module `proper` to get it running, but it seems the package available on [PyPi with the name `proper`](https://pypi.org/project/proper/) is probably not the same `proper `that you are referring to here: 

https://github.com/vortex-exoplanet/HEEPS/blob/a1307af4f3758638ec387543cb24c8e69e941489/heeps/pupil/pupil.py#L4

Which python package should I instead install to get HEEPS running?

Thanks in advance!

**Comment by GillesOrban** [comment]
Hi Kieran,

Indeed, it is not the PyPi `proper`. You will find the correct library [here](https://sourceforge.net/projects/proper-library/) (I believe it is the official repository) - the PROPER optical propagation library (in IDL, Matlab, Python; you just need the python version of course).

cheers

**Comment by astronomyk** [comment]
Hi Gilles,

thanks for the ridiculously speedy response! I'll go with that one.

Cheers,

**Comment by astronomyk** [comment]
After installing it, I noticed that it calls itself `pyproper`, which indeed is available on [pypi](https://pypi.org/project/PyPROPER/#history). However only the 3.2.5 version is on pypi, while source forge has the 3.2.7 version.

@GillesOrban Which version do you use? Or should it not make a difference?

THanks again!

**Comment by GillesOrban** [comment]
I don't think it matters much, but @ChrisDelaX will know best. On the main page, in the dependency section you will find the recommended version (3.2.6a) and the link to the download.
cheers!
