### ISSUE TITLE
Upgrade Proper v3.3

### ISSUE THREAD

**Issue by astronomyk** [vortex-exoplanet/HEEPS#37]
Hi,

It seems that the upgrades to matplotlib cause a bunch of plot statements in proper v3.2.6 to throw errors.
Will moving HEEPS to PROPER v3.3 break a whole bunch of things?

Thanks!

**Comment by ChrisDelaX** [comment]
Thanks for the heads-up! I'm not planning to move HEEPS to PROPER v3.3 for now, but I understand future users might need to. Not sure if I'll still be involved at that point.
