### ISSUE TITLE
Rename to remove "ELT"?

### ISSUE THREAD

**Issue by oabsil** [vortex-exoplanet/HEEPS#6]
As proposed by @ChrisDelaX we could rename HEEPS to become: "High-contrast End-to-End Performance Simulator". As a matter of fact, HEEPS will also be used to predict performance of instruments on other telescopes (e.g., the NEAR project at VLT).

**Comment by ppathak8** [comment]
I agree, I have changed it in the markdown file, but can't find a way to remove it from the project description. The privilege to do the same might be restricted.

**Comment by oabsil** [comment]
I am probably the only one to have permissions on that. It's now done.
