### ISSUE TITLE
bugs in 9/18 new architecture

### ISSUE THREAD

**Issue by ChrisDelaX** [vortex-exoplanet/HEEPS#7]
In this previous commit 70858bc8eb09e6f240bda4891f4b49be4ebc8446, portions of code (routines) have been converted to functions and saved in separate files, thereby adding clarity and allowing flexibility. While these changes don't break HEEPS (no error message), their implementation seem to require additional changes. In **'metis_hci.py'**, multiple calls to functions (e.g. wavefront_aberrations, coronagraph, apodization, vortex, lyotstop) return an output that is not being stored, nor used. This results in unexpected results observed, where the wavefront error doesn't seem to be affected properly by the different optical elements.

As a quick fix to allow me working on #1 , I am going to update our test file **'example_coronagraph_psf.py'** to run without calling 'metis_hci.py' anymore, leaving the issues in 'metis_hci.py' untouched. 

This issue is not high priority, and will be addressed in the next release ([HEEPS v1.1](https://github.com/vortex-exoplanet/HEEPS/milestone/2)), along with more architecture updates.

**Comment by ppathak8** [comment]
The proper routine creates an instance of a wavefront, "wfo" defined in HEEPS. It doesn't need to saved and passed.

"This results in unexpected results observed, where the wavefront error doesn't seem to be affected properly by the different optical elements." Can you tell me what kind of behaviour you observe?

**Comment by ChrisDelaX** [comment]
You're right, I figured this out as well. The bugs I was getting were
coming from another source.

However, those functions are still defined with a 'wfo' output, which is
not used. We could either change them to no output at all, or a test output
(e.g. success = Ture or False) , or call them with an output required, e.g.
wfo = function(wfo, *keys)

Le ven. 12 oct. 2018 à 15:48, Prashant Pathak <notifications@github.com> a
écrit :

**Comment by ChrisDelaX** [comment]
I am not talking about the proper routines, but the heeps ones.

**Comment by ChrisDelaX** [comment]
outdated
