### ISSUE TITLE
input/output fitsfiles containers need relative paths in HEEPS repository

### ISSUE THREAD

**Issue by ChrisDelaX** [vortex-exoplanet/HEEPS#9]
Those folders are currently created in the user local working directory.
Their paths should dynamically point to folders in the HEEPS repository.
Input/output folders will also be added to .gitignore to avoid storing fitsfiles on the Github.

**Comment by ChrisDelaX** [comment]
Will also add a user option (non-default) to specify paths to input/output fitsfiles containers, e.g. on an external storage drive.

**Comment by ppathak8** [comment]
I would recommend something relative to the current working directory. If it's in HEEPS repository by default, it will be hard access the output files, when we make it PIP installable.

**Comment by ChrisDelaX** [comment]
I did not think about this, you're right. Let's leave it by default into
the current dir, and maybe add the option to specify another place.

I am not convinced of the need to make it PIP installable. My feeling is
that it's not helpful for developers. Maybe we could talk about it together
with Olivier at some point.

Le ven. 12 oct. 2018 à 15:51, Prashant Pathak <notifications@github.com> a
écrit :

**Comment by ppathak8** [comment]
I agree, having an option to specify would be nice. 

I think PIP installation would be nice for people, who just want to use this for simple contrast analysis, without going much into details.
